base/urls.py
from django.urls import path
from .views import ProfileList,ProfileDetail,ProfileUpdate,CustomLogin,RegisterPage,UserProfile,AddImage
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm

urlpatterns=[
    path('login/',CustomLogin.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page='login'),name='logout'),
    path('home/',ProfileList.as_view(),name='home'),
    path('profile/<str:pk>',ProfileDetail.as_view(),name='profile'),
    path('profile-update/<str:pk>',ProfileUpdate.as_view(),name='profile-update'),
    path('register/',RegisterPage.as_view(),name='register'),
    path('addimage/',AddImage.as_view(),name='addimage'),
    path('userprofile/',UserProfile.as_view(),name='userprofile')

] 

insta/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
# from django.dispatch import reciever
from django.db.models.signals import post_save


class Profile(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)
    username = models.CharField(max_length= 200,null=True,blank=True)
    email=models.CharField(max_length= 200,null=True,blank=True)
    profile_image = models.ImageField(null=True,blank=True,default="user-default.png")
    Id = models.UUIDField(default = uuid.uuid4,unique = True,primary_key=True,editable=False)

    def __str__(self):
        return self.username
    # @reciever(post_save,sender=User)
    def createprofile(sender,instance,created,**kwargs):
        if created:
            user = instance
            profile =Profile.objects.create(
                user= user, 
                username = user.username
            )
    post_save.connect(createprofile,sender=User)

class Uploads(models.Model):
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE)
    featured_image = models.ImageField(null=True,blank=True)
    description = models.TextField(null=True,blank=True)
  

    def __str__(self):
        return str(self.owner)

    

base/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,CreateView,FormView
from .models import Uploads,Profile
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('home')

    def form_valid(self,form):
        user=form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage,self).form_valid(form)



class CustomLogin(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('home')


class ProfileList(LoginRequiredMixin,ListView):
    model = Profile
    context_object_name = 'profiles'
    
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['profiles']=context['profiles'].exclude(user=self.request.user)
        return context



class ProfileDetail(LoginRequiredMixin,DetailView):
    model = Profile
    context_object_name = 'profiles'

    
   

class ProfileUpdate(LoginRequiredMixin,UpdateView):
    model = Profile
    fields = ['username','email','profile_image']
    success_url = reverse_lazy('userprofile')

class AddImage(LoginRequiredMixin,CreateView):

    template_name = 'base/upload_image.html'
    model = Uploads
    fields = '__all__'
    success_url = reverse_lazy('home')




    


class UserProfile(LoginRequiredMixin,ListView):
    template_name = 'base/user_profile.html'
    model = Profile
    context_object_name = 'profiles'
   

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['profiles']=context['profiles'].get(user=self.request.user)
        return context

base/templates/base/login.html
<form method ="POST">
    {% csrf_token %}
    {{form.as_p}}
    
    <input type="submit"/>
</form>
<h3>if user is not registered</h3><br>
<a href="{% url 'register' %}">register</a>

base/templates/base/profile_detail.html
<h2><a href="{% url 'home' %}">Home</a></h2>

{{profiles.username}}
<br>
<br>
{{profiles.email}}
<br>


<!-- <a href="{% url 'addimage' %}">add image</a>  
<h2><a href="{% url 'profile-update' profiles.Id %}">Edit</a></h2> -->

<br>
<img src="{{profiles.profile_image.url}}">
<br>
<br>
<hr>



{% for i in profiles.uploads_set.all %}

<br>
<br>


<img src="{{i.featured_image.url}}">
<br>
{{i.description}}
{% endfor %}

base/templates/base/profile_form.html
<form method = 'POST' enctype = "multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>

base/templates/base/profile_list.html
<h1>instagram</h1>
{% if request.user.is_authenticated %}
<h2><a href="{% url 'userprofile' %}">Profile</a></h2>
{{request.user}}
<br>
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %}


<hr>


{% for profile in profiles %}
{% for i in profile.uploads_set.all %}
<h2><a href="{% url 'profile' profile.Id %}">{{profile.username}}</a></h2>
<br>
<img src="{{i.featured_image.url}}">
<br>
{{i.description}}
<br>
<br>
<br>
{% endfor %}
{% endfor %}

base/templates/base/register.html
<form method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register user">

</form>

base/templates/base/update_profile.html
<form method = 'POST' action="{% url 'update' %}">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">

</form>

base/templates/base/upload_image.html
<form method = 'POST'  enctype = "multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">

</form>

base/templates/base/user_profile.html
<h2><a href="{% url 'home' %}">Home</a></h2>

<h2>{{profiles.username}}</h2>
<br>
<br>
{{profiles.email}}
<br>


<a href="{% url 'addimage' %}">add image</a>
<h2><a href="{% url 'profile-update' profiles.Id %}">Edit</a></h2>

<br>
<img src="{{profiles.profile_image.url}}">
<br>
<br>
<hr>
<h2>my Album</h2>
{% for i in profiles.uploads_set.all %}

<br>
<br>


<img src="{{i.featured_image.url}}">
<br>
{{i.description}}
{% endfor %}
<hr>